version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:15-alpine
    container_name: drf-localstack-postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: drf-localstack
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - localstack
      - postgres
    env_file:
      - ./.env

volumes:
  pgdata:
