version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI
    env_file:
      - ./.env
    command: server /data --console-address ":9001"
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: drf-localstack-postgres
    restart: always
    environment:
      POSTGRES_DB: drflocalstackdb
      POSTGRES_USER: drflocalstackuser
      POSTGRES_PASSWORD: drflocalstackpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drflocalstackuser -d drflocalstackdb"]
      interval: 2s
      timeout: 5s
      retries: 10
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: drf-localstack
    command: >
      sh -c "./wait-for-it.sh postgres:5432 --
             python manage.py makemigrations &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_started
      minio:
        condition: service_started
    env_file:
      - ./.env

volumes:
  pgdata:
